/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package pkgfinal.project;
import com.mysql.jdbc.ResultSet;
import java.sql.Statement;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.time.LocalDate;
import java.util.Date;
import java.util.HashMap;
import java.util.Vector;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import java.util.UUID;


/**
 *
 * @author okyere
 */
public class add_passenger extends javax.swing.JFrame {
    PreparedStatement statement;
    Connection dbconnection;
    ResultSet result;
    /**
     * Creates new form add_passenger
     */
    public add_passenger() {
        initComponents();
        tbload();
        load_passenger_id();
        bus_number_result();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        btn_close = new javax.swing.JButton();
        jLabelkk = new javax.swing.JLabel();
        jLabel3jhv1 = new javax.swing.JLabel();
        txt_phone = new javax.swing.JTextField();
        jLabel3jhv2 = new javax.swing.JLabel();
        jLabel3jhv3 = new javax.swing.JLabel();
        jLabel3jhv4 = new javax.swing.JLabel();
        jLabel3jhv5 = new javax.swing.JLabel();
        txt_age = new javax.swing.JTextField();
        txt_lastname = new javax.swing.JTextField();
        cmb_sex = new javax.swing.JComboBox<>();
        jScrollPane1 = new javax.swing.JScrollPane();
        tb_all_buses = new javax.swing.JTable();
        btn_add = new javax.swing.JButton();
        btn_update = new javax.swing.JButton();
        btn_delete = new javax.swing.JButton();
        btn_search = new javax.swing.JButton();
        txt_search = new javax.swing.JTextField();
        jLabel3jhv6 = new javax.swing.JLabel();
        txt_firstname = new javax.swing.JTextField();
        txt_address = new javax.swing.JTextField();
        txt_passenger_id = new javax.swing.JTextField();
        jPanel3 = new javax.swing.JPanel();
        jLabelkk1 = new javax.swing.JLabel();
        jLabel3jhv10 = new javax.swing.JLabel();
        jLabel3jhv11 = new javax.swing.JLabel();
        jLabel3jhv12 = new javax.swing.JLabel();
        jLabel3jhv13 = new javax.swing.JLabel();
        jLabel3jhv14 = new javax.swing.JLabel();
        cmb_category = new javax.swing.JComboBox<>();
        cmb_payment = new javax.swing.JComboBox<>();
        llb_price = new javax.swing.JLabel();
        cmb_bus_number = new javax.swing.JComboBox<>();
        cmb_passenger_id = new javax.swing.JComboBox<>();
        txt_bus_id = new javax.swing.JTextField();
        llb_refresh_combo = new javax.swing.JLabel();
        jLabel3jhv16 = new javax.swing.JLabel();
        txt_bus_source = new javax.swing.JTextField();
        txt_bus_destination = new javax.swing.JTextField();
        buy_ticket = new javax.swing.JButton();
        jLabel3jhv17 = new javax.swing.JLabel();
        btn_search1 = new javax.swing.JButton();
        txt_search1 = new javax.swing.JTextField();
        jScrollPane2 = new javax.swing.JScrollPane();
        tb_all_buses1 = new javax.swing.JTable();
        txt_passenger_name = new javax.swing.JTextField();
        jPanel1 = new javax.swing.JPanel();
        jPanel5 = new javax.swing.JPanel();
        bus_ticket = new javax.swing.JLabel();
        jPanel6 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jPanel7 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMaximizedBounds(new java.awt.Rectangle(0, 0, 1776, 842));
        setMaximumSize(new java.awt.Dimension(1776, 842));
        setPreferredSize(new java.awt.Dimension(1776, 842));

        jPanel2.setBackground(new java.awt.Color(23, 30, 77));

        jLabel2.setBackground(new java.awt.Color(0, 0, 0));
        jLabel2.setFont(new java.awt.Font("Helvetica Neue", 1, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("User Dashboard");

        jLabel1.setBackground(new java.awt.Color(255, 102, 102));
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Welcome:");

        btn_close.setBackground(new java.awt.Color(255, 51, 51));
        btn_close.setForeground(new java.awt.Color(255, 255, 255));
        btn_close.setText("sign out");
        btn_close.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_closeActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_close, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(16, 16, 16))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(660, 660, 660)
                .addComponent(jLabel2)
                .addContainerGap(712, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(btn_close, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(9, 9, 9)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 22, Short.MAX_VALUE)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jLabelkk.setFont(new java.awt.Font("PT Serif Caption", 1, 24)); // NOI18N
        jLabelkk.setText("Add Passenger");

        jLabel3jhv1.setFont(new java.awt.Font("Helvetica Neue", 1, 20)); // NOI18N
        jLabel3jhv1.setText("Phone No.");
        jLabel3jhv1.setPreferredSize(new java.awt.Dimension(64, 40));

        txt_phone.setFont(new java.awt.Font("Helvetica Neue", 0, 18)); // NOI18N
        txt_phone.setMinimumSize(new java.awt.Dimension(64, 40));
        txt_phone.setPreferredSize(new java.awt.Dimension(64, 40));

        jLabel3jhv2.setFont(new java.awt.Font("Helvetica Neue", 1, 20)); // NOI18N
        jLabel3jhv2.setText("Age");
        jLabel3jhv2.setPreferredSize(new java.awt.Dimension(64, 40));

        jLabel3jhv3.setFont(new java.awt.Font("Helvetica Neue", 1, 20)); // NOI18N
        jLabel3jhv3.setText("Last Name");
        jLabel3jhv3.setPreferredSize(new java.awt.Dimension(64, 40));

        jLabel3jhv4.setFont(new java.awt.Font("Helvetica Neue", 1, 20)); // NOI18N
        jLabel3jhv4.setText("Address");
        jLabel3jhv4.setPreferredSize(new java.awt.Dimension(64, 40));

        jLabel3jhv5.setFont(new java.awt.Font("Helvetica Neue", 1, 20)); // NOI18N
        jLabel3jhv5.setText("Sex");
        jLabel3jhv5.setPreferredSize(new java.awt.Dimension(64, 40));

        txt_age.setFont(new java.awt.Font("Helvetica Neue", 0, 18)); // NOI18N
        txt_age.setMinimumSize(new java.awt.Dimension(64, 40));
        txt_age.setPreferredSize(new java.awt.Dimension(64, 40));

        txt_lastname.setFont(new java.awt.Font("Helvetica Neue", 0, 18)); // NOI18N
        txt_lastname.setMinimumSize(new java.awt.Dimension(64, 40));
        txt_lastname.setPreferredSize(new java.awt.Dimension(64, 40));

        cmb_sex.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "-- Select --", "Male", "Female" }));
        cmb_sex.setPreferredSize(new java.awt.Dimension(64, 40));
        cmb_sex.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmb_sexActionPerformed(evt);
            }
        });

        tb_all_buses.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null}
            },
            new String [] {
                "Pass ID", "First Name", "Last Name", "Phone", "Sex", "Age", "Address"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tb_all_buses.addAncestorListener(new javax.swing.event.AncestorListener() {
            public void ancestorAdded(javax.swing.event.AncestorEvent evt) {
                tb_all_busesAncestorAdded(evt);
            }
            public void ancestorMoved(javax.swing.event.AncestorEvent evt) {
            }
            public void ancestorRemoved(javax.swing.event.AncestorEvent evt) {
            }
        });
        tb_all_buses.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tb_all_busesMouseClicked(evt);
            }
        });
        tb_all_buses.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                tb_all_busesPropertyChange(evt);
            }
        });
        jScrollPane1.setViewportView(tb_all_buses);

        btn_add.setBackground(new java.awt.Color(204, 204, 204));
        btn_add.setFont(new java.awt.Font("Helvetica Neue", 1, 18)); // NOI18N
        btn_add.setForeground(new java.awt.Color(255, 255, 255));
        btn_add.setText("save");
        btn_add.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_addActionPerformed(evt);
            }
        });

        btn_update.setBackground(new java.awt.Color(51, 51, 255));
        btn_update.setFont(new java.awt.Font("Helvetica Neue", 1, 18)); // NOI18N
        btn_update.setForeground(new java.awt.Color(255, 255, 255));
        btn_update.setText("edit");
        btn_update.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_updateActionPerformed(evt);
            }
        });

        btn_delete.setBackground(new java.awt.Color(255, 51, 51));
        btn_delete.setFont(new java.awt.Font("Helvetica Neue", 1, 18)); // NOI18N
        btn_delete.setForeground(new java.awt.Color(255, 255, 255));
        btn_delete.setText("delete");
        btn_delete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_deleteActionPerformed(evt);
            }
        });

        btn_search.setBackground(new java.awt.Color(23, 30, 77));
        btn_search.setFont(new java.awt.Font("Helvetica Neue", 1, 18)); // NOI18N
        btn_search.setForeground(new java.awt.Color(255, 255, 255));
        btn_search.setText("search");
        btn_search.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_searchActionPerformed(evt);
            }
        });

        txt_search.setFont(new java.awt.Font("Helvetica Neue", 0, 18)); // NOI18N
        txt_search.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txt_searchKeyTyped(evt);
            }
        });

        jLabel3jhv6.setFont(new java.awt.Font("Helvetica Neue", 1, 20)); // NOI18N
        jLabel3jhv6.setText("First Name");
        jLabel3jhv6.setPreferredSize(new java.awt.Dimension(64, 40));

        txt_firstname.setFont(new java.awt.Font("Helvetica Neue", 0, 18)); // NOI18N
        txt_firstname.setMinimumSize(new java.awt.Dimension(64, 40));
        txt_firstname.setPreferredSize(new java.awt.Dimension(64, 40));
        txt_firstname.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_firstnameActionPerformed(evt);
            }
        });

        txt_address.setFont(new java.awt.Font("Helvetica Neue", 0, 18)); // NOI18N
        txt_address.setMinimumSize(new java.awt.Dimension(64, 40));
        txt_address.setPreferredSize(new java.awt.Dimension(64, 40));

        txt_passenger_id.setFont(new java.awt.Font("Helvetica Neue", 0, 18)); // NOI18N
        txt_passenger_id.setMinimumSize(new java.awt.Dimension(64, 40));
        txt_passenger_id.setPreferredSize(new java.awt.Dimension(64, 40));

        jPanel3.setBackground(new java.awt.Color(0, 0, 0));
        jPanel3.setPreferredSize(new java.awt.Dimension(965, 5));

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 965, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 5, Short.MAX_VALUE)
        );

        jLabelkk1.setFont(new java.awt.Font("PT Serif Caption", 1, 24)); // NOI18N
        jLabelkk1.setText("Book Ticket ");

        jLabel3jhv10.setFont(new java.awt.Font("Helvetica Neue", 1, 20)); // NOI18N
        jLabel3jhv10.setText("Destination");
        jLabel3jhv10.setPreferredSize(new java.awt.Dimension(64, 40));

        jLabel3jhv11.setFont(new java.awt.Font("Helvetica Neue", 1, 20)); // NOI18N
        jLabel3jhv11.setText("Source");
        jLabel3jhv11.setPreferredSize(new java.awt.Dimension(64, 40));

        jLabel3jhv12.setFont(new java.awt.Font("Helvetica Neue", 1, 20)); // NOI18N
        jLabel3jhv12.setText("Passenger");
        jLabel3jhv12.setPreferredSize(new java.awt.Dimension(64, 40));

        jLabel3jhv13.setFont(new java.awt.Font("Helvetica Neue", 1, 20)); // NOI18N
        jLabel3jhv13.setText("Bus Number");
        jLabel3jhv13.setPreferredSize(new java.awt.Dimension(64, 40));

        jLabel3jhv14.setFont(new java.awt.Font("Helvetica Neue", 1, 20)); // NOI18N
        jLabel3jhv14.setText("Seat Category ");
        jLabel3jhv14.setPreferredSize(new java.awt.Dimension(64, 40));

        cmb_category.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "-- Select --", "Ac Seat ", "General Seat" }));
        cmb_category.setPreferredSize(new java.awt.Dimension(64, 40));
        cmb_category.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmb_categoryActionPerformed(evt);
            }
        });

        cmb_payment.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "-- Select --", "Cash", "Momo", "Credit Card" }));
        cmb_payment.setPreferredSize(new java.awt.Dimension(64, 40));
        cmb_payment.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmb_paymentActionPerformed(evt);
            }
        });

        llb_price.setFont(new java.awt.Font("Helvetica Neue", 1, 20)); // NOI18N
        llb_price.setText("Price :");
        llb_price.setPreferredSize(new java.awt.Dimension(64, 40));

        cmb_bus_number.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "-- Select --" }));
        cmb_bus_number.setPreferredSize(new java.awt.Dimension(64, 40));
        cmb_bus_number.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmb_bus_numberActionPerformed(evt);
            }
        });

        cmb_passenger_id.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "-- Select --" }));
        cmb_passenger_id.setPreferredSize(new java.awt.Dimension(64, 40));
        cmb_passenger_id.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                cmb_passenger_idMouseClicked(evt);
            }
        });
        cmb_passenger_id.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmb_passenger_idActionPerformed(evt);
            }
        });

        txt_bus_id.setFont(new java.awt.Font("Helvetica Neue", 0, 18)); // NOI18N
        txt_bus_id.setEnabled(false);
        txt_bus_id.setMinimumSize(new java.awt.Dimension(64, 40));
        txt_bus_id.setPreferredSize(new java.awt.Dimension(64, 40));

        llb_refresh_combo.setFont(new java.awt.Font("Helvetica Neue", 1, 24)); // NOI18N
        llb_refresh_combo.setText("🔁");
        llb_refresh_combo.setPreferredSize(new java.awt.Dimension(64, 40));
        llb_refresh_combo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                llb_refresh_comboMouseClicked(evt);
            }
        });

        jLabel3jhv16.setFont(new java.awt.Font("Helvetica Neue", 1, 20)); // NOI18N
        jLabel3jhv16.setText("ID's");
        jLabel3jhv16.setPreferredSize(new java.awt.Dimension(64, 40));

        txt_bus_source.setFont(new java.awt.Font("Helvetica Neue", 0, 18)); // NOI18N
        txt_bus_source.setEnabled(false);
        txt_bus_source.setMinimumSize(new java.awt.Dimension(64, 40));
        txt_bus_source.setPreferredSize(new java.awt.Dimension(64, 40));

        txt_bus_destination.setFont(new java.awt.Font("Helvetica Neue", 0, 18)); // NOI18N
        txt_bus_destination.setEnabled(false);
        txt_bus_destination.setMinimumSize(new java.awt.Dimension(64, 40));
        txt_bus_destination.setPreferredSize(new java.awt.Dimension(64, 40));

        buy_ticket.setBackground(new java.awt.Color(46, 0, 44));
        buy_ticket.setFont(new java.awt.Font("Helvetica Neue", 1, 18)); // NOI18N
        buy_ticket.setForeground(new java.awt.Color(255, 255, 255));
        buy_ticket.setText("Buy ");
        buy_ticket.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buy_ticketActionPerformed(evt);
            }
        });

        jLabel3jhv17.setFont(new java.awt.Font("Helvetica Neue", 1, 20)); // NOI18N
        jLabel3jhv17.setText("Payment ");
        jLabel3jhv17.setPreferredSize(new java.awt.Dimension(64, 40));

        btn_search1.setBackground(new java.awt.Color(23, 30, 77));
        btn_search1.setFont(new java.awt.Font("Helvetica Neue", 1, 18)); // NOI18N
        btn_search1.setForeground(new java.awt.Color(255, 255, 255));
        btn_search1.setText("search");
        btn_search1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_search1ActionPerformed(evt);
            }
        });

        txt_search1.setFont(new java.awt.Font("Helvetica Neue", 0, 18)); // NOI18N
        txt_search1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_search1ActionPerformed(evt);
            }
        });
        txt_search1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txt_search1KeyTyped(evt);
            }
        });

        tb_all_buses1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null}
            },
            new String [] {
                "Pass ID", "First Name", "Last Name", "Phone", "Sex", "Age", "Address"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tb_all_buses1.addAncestorListener(new javax.swing.event.AncestorListener() {
            public void ancestorAdded(javax.swing.event.AncestorEvent evt) {
                tb_all_buses1AncestorAdded(evt);
            }
            public void ancestorMoved(javax.swing.event.AncestorEvent evt) {
            }
            public void ancestorRemoved(javax.swing.event.AncestorEvent evt) {
            }
        });
        tb_all_buses1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tb_all_buses1MouseClicked(evt);
            }
        });
        tb_all_buses1.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                tb_all_buses1PropertyChange(evt);
            }
        });
        jScrollPane2.setViewportView(tb_all_buses1);

        txt_passenger_name.setFont(new java.awt.Font("Helvetica Neue", 0, 18)); // NOI18N
        txt_passenger_name.setEnabled(false);
        txt_passenger_name.setMinimumSize(new java.awt.Dimension(64, 40));
        txt_passenger_name.setPreferredSize(new java.awt.Dimension(64, 40));

        jPanel1.setBackground(new java.awt.Color(0, 91, 204));

        jPanel5.setBackground(new java.awt.Color(255, 255, 255));

        bus_ticket.setBackground(new java.awt.Color(0, 91, 204));
        bus_ticket.setFont(new java.awt.Font("Optima", 1, 36)); // NOI18N
        bus_ticket.setForeground(new java.awt.Color(0, 91, 204));
        bus_ticket.setText("Buy Ticket");
        bus_ticket.setAlignmentY(0.0F);
        bus_ticket.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                bus_ticketMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                .addContainerGap(36, Short.MAX_VALUE)
                .addComponent(bus_ticket)
                .addContainerGap(37, Short.MAX_VALUE))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(bus_ticket)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel6.setBackground(new java.awt.Color(255, 255, 255));

        jLabel3.setBackground(new java.awt.Color(0, 91, 204));
        jLabel3.setFont(new java.awt.Font("Optima", 1, 36)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 91, 204));
        jLabel3.setText("Confirm");
        jLabel3.setAlignmentY(0.0F);
        jLabel3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel3MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel3)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel3)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel7.setBackground(new java.awt.Color(255, 255, 255));

        jLabel5.setBackground(new java.awt.Color(0, 91, 204));
        jLabel5.setFont(new java.awt.Font("Optima", 1, 36)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(0, 91, 204));
        jLabel5.setText("Bookings");
        jLabel5.setAlignmentY(0.0F);
        jLabel5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel5MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel5)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel5)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(85, 85, 85)
                .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(81, 81, 81)
                .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(240, 240, 240))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(238, 238, 238)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(layout.createSequentialGroup()
                .addGap(275, 275, 275)
                .addComponent(jLabel3jhv6, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(txt_firstname, javax.swing.GroupLayout.PREFERRED_SIZE, 228, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(40, 40, 40)
                .addComponent(jLabel3jhv5, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(12, 12, 12)
                .addComponent(cmb_sex, javax.swing.GroupLayout.PREFERRED_SIZE, 235, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(40, 40, 40)
                .addComponent(btn_add, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(layout.createSequentialGroup()
                .addGap(275, 275, 275)
                .addComponent(jLabel3jhv3, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(txt_lastname, javax.swing.GroupLayout.PREFERRED_SIZE, 228, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(40, 40, 40)
                .addComponent(jLabel3jhv2, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(txt_age, javax.swing.GroupLayout.PREFERRED_SIZE, 229, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(40, 40, 40)
                .addComponent(btn_update, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(layout.createSequentialGroup()
                .addGap(275, 275, 275)
                .addComponent(jLabel3jhv1, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(txt_phone, javax.swing.GroupLayout.PREFERRED_SIZE, 228, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(40, 40, 40)
                .addComponent(jLabel3jhv4, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(txt_address, javax.swing.GroupLayout.PREFERRED_SIZE, 229, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(40, 40, 40)
                .addComponent(btn_delete, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(layout.createSequentialGroup()
                .addGap(244, 244, 244)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(36, 36, 36)
                        .addComponent(jLabelkk, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(280, 280, 280)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(2, 2, 2)
                                        .addComponent(jLabelkk1))
                                    .addComponent(jLabel3jhv16, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(6, 6, 6)
                                .addComponent(llb_refresh_combo, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(6, 6, 6)
                                .addComponent(cmb_passenger_id, javax.swing.GroupLayout.PREFERRED_SIZE, 192, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(153, 153, 153)
                                .addComponent(jLabel3jhv12, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(36, 36, 36)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(3, 3, 3)
                                        .addComponent(txt_bus_id, javax.swing.GroupLayout.PREFERRED_SIZE, 0, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(txt_passenger_name, javax.swing.GroupLayout.PREFERRED_SIZE, 228, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel3jhv13, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(14, 14, 14)
                                .addComponent(cmb_bus_number, javax.swing.GroupLayout.PREFERRED_SIZE, 228, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(152, 152, 152)
                                .addComponent(jLabel3jhv14, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(11, 11, 11)
                                .addComponent(cmb_category, javax.swing.GroupLayout.PREFERRED_SIZE, 228, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel3jhv11, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(38, 38, 38)
                                .addComponent(txt_bus_source, javax.swing.GroupLayout.PREFERRED_SIZE, 228, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(153, 153, 153)
                                .addComponent(jLabel3jhv17, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(36, 36, 36)
                                .addComponent(cmb_payment, javax.swing.GroupLayout.PREFERRED_SIZE, 228, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel3jhv10, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(38, 38, 38)
                                .addComponent(txt_bus_destination, javax.swing.GroupLayout.PREFERRED_SIZE, 228, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(153, 153, 153)
                                .addComponent(llb_price, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(7, 7, 7)
                                .addComponent(buy_ticket, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 550, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                .addGroup(layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(btn_search1)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addComponent(txt_search1, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap())
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(414, 414, 414)
                        .addComponent(txt_passenger_id, javax.swing.GroupLayout.PREFERRED_SIZE, 0, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btn_search)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txt_search, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(1215, 1215, 1215)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 550, javax.swing.GroupLayout.PREFERRED_SIZE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30)
                .addComponent(jLabelkk)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txt_passenger_id, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(12, 12, 12)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3jhv6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(2, 2, 2)
                        .addComponent(txt_firstname, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(7, 7, 7)
                        .addComponent(jLabel3jhv5, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(cmb_sex, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(3, 3, 3)
                        .addComponent(btn_add, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(17, 17, 17)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3jhv3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(2, 2, 2)
                        .addComponent(txt_lastname, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(3, 3, 3)
                        .addComponent(jLabel3jhv2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(5, 5, 5)
                        .addComponent(txt_age, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(1, 1, 1)
                        .addComponent(btn_update, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(17, 17, 17)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3jhv1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(2, 2, 2)
                        .addComponent(txt_phone, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(jLabel3jhv4, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(2, 2, 2)
                        .addComponent(txt_address, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(1, 1, 1)
                        .addComponent(btn_delete, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(60, 60, 60)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(50, 50, 50)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabelkk1)
                                .addGap(17, 17, 17)
                                .addComponent(jLabel3jhv16, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(48, 48, 48)
                                .addComponent(llb_refresh_combo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(49, 49, 49)
                                .addComponent(cmb_passenger_id, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(45, 45, 45)
                                .addComponent(jLabel3jhv12, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(7, 7, 7)
                                .addComponent(txt_bus_id, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, 0)
                                .addComponent(txt_passenger_name, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(22, 22, 22)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(4, 4, 4)
                                .addComponent(jLabel3jhv13, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(4, 4, 4)
                                .addComponent(cmb_bus_number, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jLabel3jhv14, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(5, 5, 5)
                                .addComponent(cmb_category, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(17, 17, 17)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(9, 9, 9)
                                .addComponent(jLabel3jhv11, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(11, 11, 11)
                                .addComponent(txt_bus_source, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jLabel3jhv17, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(5, 5, 5)
                                .addComponent(cmb_payment, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(12, 12, 12)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(8, 8, 8)
                                .addComponent(jLabel3jhv10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(10, 10, 10)
                                .addComponent(txt_bus_destination, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(9, 9, 9)
                                .addComponent(llb_price, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(buy_ticket, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(12, 12, 12)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txt_search1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btn_search1))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 240, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(0, 58, Short.MAX_VALUE))
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGap(172, 172, 172)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txt_search, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_search))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 234, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

     public void book_view(){
        dispose();
        book_ticket book_view = new book_ticket();
        book_view.setLocationRelativeTo(null);
        book_view.setVisible(true);
    }
     
    public void passenger_view(){
        dispose();
        add_passenger passenger_view = new add_passenger();
        passenger_view.setLocationRelativeTo(null);
        passenger_view.setVisible(true);
    }
    private void cmb_sexActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmb_sexActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cmb_sexActionPerformed

    private void tb_all_busesAncestorAdded(javax.swing.event.AncestorEvent evt) {//GEN-FIRST:event_tb_all_busesAncestorAdded
        // TODO add your handling code here:
    }//GEN-LAST:event_tb_all_busesAncestorAdded

    private void tb_all_busesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tb_all_busesMouseClicked
//         TODO add your handling code here:
        int selectedRow = tb_all_buses.getSelectedRow();
        if (selectedRow != -1) {
            DefaultTableModel model = (DefaultTableModel) tb_all_buses.getModel();           
            txt_passenger_id.setText(model.getValueAt(selectedRow, 0).toString());            
            txt_firstname.setText(model.getValueAt(selectedRow, 1).toString());            
            txt_lastname.setText(model.getValueAt(selectedRow, 2).toString());
            txt_phone.setText(model.getValueAt(selectedRow, 3).toString());
            cmb_sex.setSelectedItem(model.getValueAt(selectedRow, 5).toString());
            txt_age.setText(model.getValueAt(selectedRow, 4).toString());
            txt_address.setText(model.getValueAt(selectedRow, 6).toString());

    }//GEN-LAST:event_tb_all_busesMouseClicked
    }
    private void tb_all_busesPropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_tb_all_busesPropertyChange
        // TODO add your handling code here:
    }//GEN-LAST:event_tb_all_busesPropertyChange

    private void btn_addActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_addActionPerformed
        // TODO add your handling code here:
        
        String firstname = txt_firstname.getText();
        String lastname = txt_lastname.getText();
        String phone = txt_phone.getText();
        String sex = cmb_sex.getSelectedItem().toString();
        String age = txt_age.getText();
        String address = txt_address.getText();
        
        if(firstname.equals("")){
            JOptionPane.showMessageDialog(null, "Field can't be empty");
        }else if(lastname.equals("")){
            JOptionPane.showMessageDialog(null, "Field can't be empty");
        }else if(phone.equals("")){
            JOptionPane.showMessageDialog(null, "Field can't be empty");
        }else if(address.equals("")){
            JOptionPane.showMessageDialog(null, "Field can't be empty");
        }else{
            try{
                open_connection();
                String query_command = "INSERT INTO passenger(firstname, lastname, passenger_sex, passenger_age, phone, passenger_address) VALUES(?, ?, ?, ?, ?, ?)";
                statement = dbconnection.prepareStatement(query_command);
                
                statement.setString(1, firstname);
                statement.setString(2, lastname);
                statement.setString(3, sex);
                statement.setString(4 ,age);
                statement.setString(5, phone);
                statement.setString(6, address);
                                                
                int result = statement.executeUpdate();
                if(result == 1){
                    JOptionPane.showMessageDialog(null, "New Passenger Added");
                    clear_fields();
                    tbload();
                    
                }else{
                    JOptionPane.showMessageDialog(null, "Unable to Add Passenger");
                    clear_fields();
                }
                
            }catch(Exception ex){
                JOptionPane.showMessageDialog(null, "Error" + ex );
            }finally{
                close_connection();
            }
        }

    }//GEN-LAST:event_btn_addActionPerformed

    public void signout(){
        dispose();
        login_user user_view = new login_user();
        user_view.setLocationRelativeTo(null);
        user_view.setVisible(true);
    }
    
    // function for opening database connection
    public void open_connection(){
        try{
//            Class.forName("com.mysql.jdbc.Driver");
            String databaseUrl = "jdbc:mysql://localhost/busmanagementsystem";
            dbconnection = DriverManager.getConnection(databaseUrl, "root", "");
        }catch(Exception ex){
            JOptionPane.showMessageDialog(null, "Error" +ex);
        }
        
    }
    
    //function for closing database connection
    public void close_connection(){
        try{
            dbconnection.close();
        }catch(Exception ex){
            JOptionPane.showMessageDialog(null, "Error"  + ex);
        }
    }
    
    public void clear_fields(){
        txt_firstname.setText("");
        txt_lastname.setText("");
        txt_phone.setText("");
        txt_address.setText("");
        txt_age.setText("");
        cmb_sex.setSelectedItem(-1);
    }
     
    // method to load data into table form database
    public void tbload(){
    
    try{
        open_connection();
        
        DefaultTableModel table_data = (DefaultTableModel) tb_all_buses.getModel();        
        table_data.setRowCount(0);
        String query_command = "SELECT passenger_id, firstname, lastname, phone, passenger_age, passenger_sex , passenger_address FROM passenger ";        
        statement = dbconnection.prepareStatement(query_command);
        java.sql.ResultSet result = statement.executeQuery(query_command);
      
        while(result.next()){
            Vector v = new Vector();
            v.add(result.getString(1));
            v.add(result.getString(2));
            v.add(result.getString(3));
            v.add(result.getString(4));
            v.add(result.getString(5));
            v.add(result.getString(6));
            v.add(result.getString(7));            
            
            table_data.addRow(v);
    }
        
    }catch(Exception ex){
    JOptionPane.showMessageDialog(null, "Error"  + ex);
    }finally{
        close_connection();
    }
    }
    
    public void search_data(){
        String search = txt_search.getText();  
    try{
        open_connection();
        
        DefaultTableModel table_data = (DefaultTableModel) tb_all_buses.getModel();        
        table_data.setRowCount(0);
        String query_command = "SELECT * FROM passenger WHERE passenger_id LIKE '%" +search+ "%' OR firstname LIKE '%" +search+ "%' OR lastname LIKE '%" +search+ "%' OR passenger_age LIKE '%" +search+ "%' OR passenger_sex LIKE '%" +search+ "%' OR phone LIKE '%" +search+ "%' OR passenger_address LIKE '%" +search+ "%'   ";
                
        statement = dbconnection.prepareStatement(query_command);               
        java.sql.ResultSet result = statement.executeQuery(query_command);
        
        while(result.next()){
            Vector v = new Vector();
            v.add(result.getString(1));
            v.add(result.getString(2));
            v.add(result.getString(3));
            v.add(result.getString(4));
            v.add(result.getString(5));
            v.add(result.getString(6));
            v.add(result.getString(7));
            v.add(result.getString(8));
            
            table_data.addRow(v);
    }
    }catch(Exception ex){
        JOptionPane.showMessageDialog(null, "Error" + ex );
    }finally{
        close_connection();
    }
    }
    
    private void btn_updateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_updateActionPerformed
        // TODO add your handling code here:
        String passenger_id = txt_passenger_id.getText();
        String firstname = txt_firstname.getText();
        String lastname = txt_lastname.getText();
        String phone = txt_phone.getText();
        String sex = cmb_sex.getSelectedItem().toString();
        String age = txt_age.getText();
        String address = txt_address.getText();

        try{
            open_connection();
            String query_command = "UPDATE passenger SET firstname = ? , lastname = ? , phone = ? , passenger_sex = ? , passenger_age = ? , passenger_address = ? WHERE passenger_id = '"+passenger_id+"' ";
            statement = dbconnection.prepareStatement(query_command);
            statement.setString(1, firstname);
            statement.setString(2, lastname);          
            statement.setString(3, phone);
            statement.setString(4, sex);
            statement.setString(5, age);
            statement.setString(6, address);

            int result = statement.executeUpdate();
            if(result == 1){
                JOptionPane.showMessageDialog(null, "Passenger Details Edit Successful");
                clear_fields();
                tbload();
            }else{
                JOptionPane.showMessageDialog(null, "Unable to Edit Passenger Details");
                clear_fields();
                tbload();
            }
        }catch(Exception ex){
            JOptionPane.showConfirmDialog(null, "Error" +ex);
        }
    }//GEN-LAST:event_btn_updateActionPerformed

    private void btn_deleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_deleteActionPerformed
        // TODO add your handling code here:
        String passenger_id = txt_passenger_id.getText();        
        
        try{
            open_connection();
            String query_command = "DELETE FROM passenger WHERE passenger_id = ? ";
            statement = dbconnection.prepareStatement(query_command);
            statement.setString(1, passenger_id);            
            
            int result = statement.executeUpdate();
            if(result == 1){
                JOptionPane.showMessageDialog(null, "Passenger Deleted");
                clear_fields();
                tbload();
            }else{
                    JOptionPane.showMessageDialog(null, "Unable to delete Passenger");
                    clear_fields();
                    tbload();
                }            
        }catch(Exception ex){
            JOptionPane.showConfirmDialog(null, "Error" +ex);
        }
                      
    }//GEN-LAST:event_btn_deleteActionPerformed

    private void btn_searchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_searchActionPerformed
        // TODO add your handling code here:
        search_data();
    }//GEN-LAST:event_btn_searchActionPerformed

    private void txt_searchKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_searchKeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_searchKeyTyped

//        get passenger_id information into combo box 
    public void load_passenger_id(){
        try{
            open_connection();
            String Passenger = cmb_passenger_id.getSelectedItem().toString(); 
            String query_command = "SELECT passenger_id, firstname from passenger";
            statement = dbconnection.prepareStatement(query_command);               
            java.sql.ResultSet result = statement.executeQuery(query_command);
            
            // get information into a hashmap 
            HashMap<String, String> passengerMap = new HashMap<>();
            
        while(result.next()){
            String passengerId = result.getString("passenger_id");
            String passengerName = result.getString("firstname");
            passengerMap.put(passengerId, passengerName);
            
            cmb_passenger_id.addItem(passengerId);

        }      
        }catch(Exception ex){
            JOptionPane.showConfirmDialog(null, "Error" +ex);
        }finally{
            close_connection();
        }
    }
    
    //        get passenger_id information into combo box 
    public void load_source_destination(){
        try{
            open_connection();
            String Passenger = cmb_passenger_id.getSelectedItem().toString(); 
            String query_command = "SELECT bus_source, bus_destination from buses";
            statement = dbconnection.prepareStatement(query_command);               
            java.sql.ResultSet result = statement.executeQuery(query_command);
            
            // get information into a hashmap 
            HashMap<String, String> passengerMap = new HashMap<>();
            
        while(result.next()){
            String passengerId = result.getString("passenger_id");
            String passengerName = result.getString("firstname");
            passengerMap.put(passengerId, passengerName);
            
            cmb_passenger_id.addItem(passengerId);

        }   
            
        }catch(Exception ex){
            JOptionPane.showConfirmDialog(null, "Error" +ex);
        }finally{
            close_connection();
        }
    }
    private void cmb_categoryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmb_categoryActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cmb_categoryActionPerformed

    private void cmb_paymentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmb_paymentActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cmb_paymentActionPerformed

    private void cmb_bus_numberActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmb_bus_numberActionPerformed
        // TODO add your handling code here:
        //get information related the user id selected into the text field
        try {
        open_connection();
            String bus_number = cmb_bus_number.getSelectedItem().toString(); 
        String query_command = "SELECT bus_source, bus_destination, price, bus_id FROM buses WHERE  bus_number= ?";
        statement = dbconnection.prepareStatement(query_command); 
        statement.setString(1, bus_number);      
        java.sql.ResultSet result = statement.executeQuery();
        
        HashMap<String, String> bus_data = new HashMap<>();        
        
        if (result.next()) {
            String bus_source_result = result.getString("bus_source");
            String bus_destination_result = result.getString("bus_destination");
            String bus_price_result = result.getString("price");
            String bus_id_result = result.getString("bus_id");
            
            bus_data.put(bus_source_result, bus_destination_result );
            bus_data.put(bus_price_result, bus_id_result);
            txt_bus_source.setText(bus_source_result);
            txt_bus_destination.setText(bus_destination_result);
            llb_price.setText("Price :" + bus_price_result);
            txt_bus_id.setText(bus_id_result);
              
        } else {
            // Handle case where no results are found for the given user ID
            txt_bus_source.setText("No destination found");
            txt_bus_destination.setText("No destination found");
        }
    } catch (Exception ex) {
        JOptionPane.showMessageDialog(null, "Error: " + ex.getMessage());
    } finally {
        close_connection();
    }   
    }//GEN-LAST:event_cmb_bus_numberActionPerformed

    public void bus_number_result(){
         try{
            open_connection();
            String Passenger = cmb_passenger_id.getSelectedItem().toString(); 
            String query_command = "SELECT bus_number from buses";
            statement = dbconnection.prepareStatement(query_command);               
            java.sql.ResultSet result = statement.executeQuery(query_command);
            
            // get information into a hashmap 
            HashMap<String, String> passengerMap = new HashMap<>();
            
        while(result.next()){            
            String bus_number_data = result.getString("bus_number");
            passengerMap.put(bus_number_data, "null");
            
            cmb_bus_number.addItem(bus_number_data);

        }   
            
        }catch(Exception ex){
            JOptionPane.showConfirmDialog(null, "Error" +ex);
        }finally{
            close_connection();
        }
    }                    

    private void cmb_passenger_idActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmb_passenger_idActionPerformed
        // TODO add your handling code here:
        //get information related the user id selected into the text field
        try {
        open_connection();
        String Passenger = cmb_passenger_id.getSelectedItem().toString(); 
        String query_command = "SELECT CONCAT(firstname ,' ' , lastname) AS Name FROM `passenger` WHERE passenger_id = ?";
        statement = dbconnection.prepareStatement(query_command); 
        statement.setString(1, Passenger);      
        java.sql.ResultSet result = statement.executeQuery();
        
        if (result.next()) {
            txt_passenger_name.setText(result.getString("Name"));
              
        } else {
            // Handle case where no results are found for the given user ID
            txt_passenger_name.setText("No passenger found");
        }
    } catch (Exception ex) {
        JOptionPane.showMessageDialog(null, "Error: " + ex.getMessage());
    } finally {
        close_connection();
    }          
    }//GEN-LAST:event_cmb_passenger_idActionPerformed

    private void cmb_passenger_idMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cmb_passenger_idMouseClicked
        // TODO add your handling code here:

    }//GEN-LAST:event_cmb_passenger_idMouseClicked

    private void llb_refresh_comboMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_llb_refresh_comboMouseClicked
        // TODO add your handling code here:
        dispose();
        add_passenger passenger_view = new add_passenger();
        passenger_view.setLocationRelativeTo(null);
        passenger_view.setVisible(true);
    }//GEN-LAST:event_llb_refresh_comboMouseClicked

    // Method to generate a new ticket number
    public static String generate_ticket_number() {
        // Generate a unique identifier
        int ticketCounter = 100;
        String uniqueID = UUID.randomUUID().toString().substring(0, 7).toUpperCase(); // Using first 8 characters of UUID

        // Increment ticket counter
        ticketCounter++;

        // Combine identifier, timestamp, and ticket counter to form ticket number
        String ticketNumber = uniqueID + "-" + ticketCounter;

        return ticketNumber;
    }
    
    private void buy_ticketActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buy_ticketActionPerformed
        // TODO add your handling code here:
        try{            
        open_connection();
        
        java.sql.Timestamp currentDate = new java.sql.Timestamp(System.currentTimeMillis());
        
        String passenger_id = cmb_passenger_id.getSelectedItem().toString();
        String bus_number = cmb_bus_number.getSelectedItem().toString();                
        String source = txt_bus_source.getText();
        String destination = txt_bus_destination.getText();
        String seat_category = cmb_category.getSelectedItem().toString();        
        String payment = cmb_payment.getSelectedItem().toString();        
        String bus_id = txt_bus_id.getText();
        String ticket_number = generate_ticket_number();
        
        
        if(passenger_id.equals("")){
            JOptionPane.showMessageDialog(null, "Field can't be empty");
        }else if(bus_number.equals("")){
            JOptionPane.showMessageDialog(null, "Field can't be empty");
        }else if(source.equals("")){
            JOptionPane.showMessageDialog(null, "Field can't be empty");
        }else if(destination.equals("")){
            JOptionPane.showMessageDialog(null, "Field can't be empty");
        }else{
            try{                               
                
                String query_command = "INSERT INTO ticket(ticket_number, seat_category, source, destination, bus_id, passenger_id, payment_method, date_booked) VALUES(?, ?, ?, ?, ?, ?, ?, ?)";
                statement = dbconnection.prepareStatement(query_command);
                
                statement.setString(1, ticket_number);
                statement.setString(2, seat_category);
                statement.setString(3, source);
                statement.setString(4 ,destination);                
                statement.setString(5,bus_id);
                statement.setString(6, passenger_id);
                statement.setString(7, payment);
                statement.setTimestamp(8, currentDate);
                                                
                int result = statement.executeUpdate();
                if(result == 1){                    
                    JOptionPane.showMessageDialog(null, "Ticket Booked");
                    clear_fields();
                    tbload();
                    
                }else{
                    JOptionPane.showMessageDialog(null, "Unable to Book Ticket ");
                    clear_fields();
                }
                
            }catch(Exception ex){
                JOptionPane.showMessageDialog(null, "Error" + ex );
            }finally{
                close_connection();
            }
        }
            
        }catch(Exception ex){
            JOptionPane.showMessageDialog(null, "Error: " + ex.getMessage());
        }finally{
            close_connection();
        }
    }//GEN-LAST:event_buy_ticketActionPerformed

    private void btn_search1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_search1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_search1ActionPerformed

    private void txt_search1KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_search1KeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_search1KeyTyped

    private void tb_all_buses1AncestorAdded(javax.swing.event.AncestorEvent evt) {//GEN-FIRST:event_tb_all_buses1AncestorAdded
        // TODO add your handling code here:
    }//GEN-LAST:event_tb_all_buses1AncestorAdded

    private void tb_all_buses1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tb_all_buses1MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_tb_all_buses1MouseClicked

    private void tb_all_buses1PropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_tb_all_buses1PropertyChange
        // TODO add your handling code here:
    }//GEN-LAST:event_tb_all_buses1PropertyChange

    private void bus_ticketMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bus_ticketMouseClicked
        // TODO add your handling code here:
        passenger_view();
    }//GEN-LAST:event_bus_ticketMouseClicked

    private void jLabel3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel3MouseClicked
        // TODO add your handling code here:
        book_view();
    }//GEN-LAST:event_jLabel3MouseClicked

    private void jLabel5MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel5MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel5MouseClicked

    private void btn_closeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_closeActionPerformed
        // TODO add your handling code here:
        signout();

    }//GEN-LAST:event_btn_closeActionPerformed

    private void txt_firstnameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_firstnameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_firstnameActionPerformed

    private void txt_search1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_search1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_search1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(add_passenger.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(add_passenger.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(add_passenger.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(add_passenger.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new add_passenger().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_add;
    private javax.swing.JButton btn_close;
    private javax.swing.JButton btn_delete;
    private javax.swing.JButton btn_search;
    private javax.swing.JButton btn_search1;
    private javax.swing.JButton btn_update;
    private javax.swing.JLabel bus_ticket;
    private javax.swing.JButton buy_ticket;
    private javax.swing.JComboBox<String> cmb_bus_number;
    private javax.swing.JComboBox<String> cmb_category;
    private javax.swing.JComboBox<String> cmb_passenger_id;
    private javax.swing.JComboBox<String> cmb_payment;
    private javax.swing.JComboBox<String> cmb_sex;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel3jhv1;
    private javax.swing.JLabel jLabel3jhv10;
    private javax.swing.JLabel jLabel3jhv11;
    private javax.swing.JLabel jLabel3jhv12;
    private javax.swing.JLabel jLabel3jhv13;
    private javax.swing.JLabel jLabel3jhv14;
    private javax.swing.JLabel jLabel3jhv16;
    private javax.swing.JLabel jLabel3jhv17;
    private javax.swing.JLabel jLabel3jhv2;
    private javax.swing.JLabel jLabel3jhv3;
    private javax.swing.JLabel jLabel3jhv4;
    private javax.swing.JLabel jLabel3jhv5;
    private javax.swing.JLabel jLabel3jhv6;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabelkk;
    private javax.swing.JLabel jLabelkk1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel llb_price;
    private javax.swing.JLabel llb_refresh_combo;
    private javax.swing.JTable tb_all_buses;
    private javax.swing.JTable tb_all_buses1;
    private javax.swing.JTextField txt_address;
    private javax.swing.JTextField txt_age;
    private javax.swing.JTextField txt_bus_destination;
    private javax.swing.JTextField txt_bus_id;
    private javax.swing.JTextField txt_bus_source;
    private javax.swing.JTextField txt_firstname;
    private javax.swing.JTextField txt_lastname;
    private javax.swing.JTextField txt_passenger_id;
    private javax.swing.JTextField txt_passenger_name;
    private javax.swing.JTextField txt_phone;
    private javax.swing.JTextField txt_search;
    private javax.swing.JTextField txt_search1;
    // End of variables declaration//GEN-END:variables
}
